import fs from 'node:fs';
import { KASPAD_ARGS_FILE, PORTS_OVERRIDE } from './paths.js';
import { NETWORKS } from './store.js';

export const ports = (cfg) => NETWORKS[cfg.network] ?? NETWORKS.mainnet;

const isBlank = (v) => v === null || v === undefined || `${v}`.trim() === '';

/**
 * Turns the stored node config into the kaspad command line.
 *
 * Every listener binds 0.0.0.0 inside the container. That is not the same as
 * being reachable from the internet: what makes a port public is the published
 * mapping in the compose override (see `renderPortsOverride`). Binding all of
 * them keeps them addressable on the internal docker network, which is how the
 * manager reaches wRPC-JSON and how the nginx proxy reaches any of them.
 *
 * --appdir and --yes are NOT emitted here; the container entrypoint always
 * prepends them. --utxoindex used to be forced the same way and is a setting
 * now, so it is emitted from here like any other flag.
 */
export function buildArgs(cfg) {
    const p = ports(cfg);
    const args = [...(NETWORKS[cfg.network]?.args ?? [])];

    args.push(`--listen=0.0.0.0:${p.p2p}`);
    if (cfg.flags.utxoindex) args.push('--utxoindex');

    if (cfg.services.grpc) {
        args.push(`--rpclisten=0.0.0.0:${p.grpc}`);
    } else {
        args.push('--nogrpc');
    }
    if (cfg.services.borsh) args.push(`--rpclisten-borsh=0.0.0.0:${p.borsh}`);
    // wRPC-JSON is the manager's control channel, so it is unconditional.
    args.push(`--rpclisten-json=0.0.0.0:${p.json}`);

    const f = cfg.flags;
    if (f.archival) args.push('--archival');
    if (f.unsaferpc) args.push('--unsaferpc');
    if (f.perfMetrics) args.push('--perf-metrics');
    if (f.disableUpnp) args.push('--disable-upnp');
    if (f.noDnsSeed) args.push('--nodnsseed');
    if (f.enableUnsyncedMining) args.push('--enable-unsynced-mining');
    if (f.sanity) args.push('--sanity');
    if (f.noLogFiles) args.push('--nologfiles');

    const t = cfg.tuning;
    if (!isBlank(t.logLevel)) args.push(`--loglevel=${t.logLevel}`);
    if (!isBlank(t.outpeers)) args.push(`--outpeers=${t.outpeers}`);
    if (!isBlank(t.maxinpeers)) args.push(`--maxinpeers=${t.maxinpeers}`);
    if (!isBlank(t.rpcmaxclients)) args.push(`--rpcmaxclients=${t.rpcmaxclients}`);
    if (!isBlank(t.maxTrackedAddresses) && Number(t.maxTrackedAddresses) > 0) {
        args.push(`--max-tracked-addresses=${t.maxTrackedAddresses}`);
    }
    if (!isBlank(t.ramScale) && Number(t.ramScale) !== 1) args.push(`--ram-scale=${t.ramScale}`);
    if (!isBlank(t.retentionPeriodDays)) args.push(`--retention-period-days=${t.retentionPeriodDays}`);
    if (!isBlank(t.asyncThreads)) args.push(`--async-threads=${t.asyncThreads}`);
    if (!isBlank(t.rocksdbPreset)) args.push(`--rocksdb-preset=${t.rocksdbPreset}`);

    const n = cfg.peering;
    if (!isBlank(n.externalip)) args.push(`--externalip=${n.externalip.trim()}`);
    if (!isBlank(n.uacomment)) args.push(`--uacomment=${n.uacomment.trim()}`);
    for (const peer of n.connectPeers ?? []) if (!isBlank(peer)) args.push(`--connect=${peer.trim()}`);
    for (const peer of n.addPeers ?? []) if (!isBlank(peer)) args.push(`--addpeer=${peer.trim()}`);

    for (const extra of cfg.extraArgs ?? []) if (!isBlank(extra)) args.push(extra.trim());

    return args;
}

export function writeArgsFile(cfg) {
    const args = buildArgs(cfg);
    const header = [
        '# Generated by the Kaspa Node Control panel - edits here are overwritten.',
        '# One argument per line. --appdir and --yes are always added by the',
        '# container entrypoint and cannot be disabled.',
        // kaspad has no --no-utxoindex, so "off" can only ever look like an
        // absent line -- which is also what every args file written before the
        // setting existed looks like. This marker is how the entrypoint tells
        // the two apart: with it, absence means off; without it, absence means
        // an old file whose node has been indexing all along, and the
        // entrypoint keeps forcing it on.
        `# utxoindex-managed: ${cfg.flags.utxoindex ? 'on' : 'off'}`,
        '',
    ].join('\n');
    fs.writeFileSync(KASPAD_ARGS_FILE, `${header}${args.join('\n')}\n`, 'utf8');
    return args;
}

/**
 * Compose concatenates `ports` across files, so the base compose file leaves
 * kaspad's list empty and this override owns it entirely. Rewriting this file
 * and running `docker compose up -d kaspad` is what opens or closes a port.
 */
export function renderPortsOverride(cfg) {
    const p = ports(cfg);
    const bind = cfg.expose.bindAddress || '0.0.0.0';
    const mappings = [];
    if (cfg.expose.p2p) mappings.push(p.p2p);
    if (cfg.expose.grpc && cfg.services.grpc) mappings.push(p.grpc);
    if (cfg.expose.borsh && cfg.services.borsh) mappings.push(p.borsh);
    if (cfg.expose.json) mappings.push(p.json);

    const lines = [
        '# Generated by the Kaspa Node Control panel - edits here are overwritten.',
        '# Published host ports for kaspad. Removing a mapping makes the port',
        '# reachable only from the internal docker network.',
        'services:',
        '  kaspad:',
        '    ports:',
    ];
    if (mappings.length === 0) lines.push('      []');
    for (const port of mappings) lines.push(`      - "${bind}:${port}:${port}/tcp"`);

    fs.writeFileSync(PORTS_OVERRIDE, `${lines.join('\n')}\n`, 'utf8');
    return mappings;
}

/** The ports a user has to open on their router/firewall to go public. */
export function publicPorts(cfg) {
    return portMatrix(cfg)
        .filter((e) => e.listening && e.published)
        .map(({ port, name, required }) => ({ port, name, required }));
}

/**
 * Every port the node can offer, with both of its independent states.
 *
 * There really are two, and collapsing them would cost real capability:
 *   listening  the kaspad argument -- whether the service is bound at all,
 *              which is what the stratum bridge (gRPC) and the KaChat indexer
 *              (wRPC Borsh) need over the internal network;
 *   published  whether Docker maps it to a host port, which is the only thing
 *              that decides if the outside world can reach it.
 *
 * Listing off ports too is deliberate: showing only enabled ones would remove a
 * port's own row the moment it was switched off, leaving no way back on.
 */
export function portMatrix(cfg) {
    const p = ports(cfg);
    const row = (key, port, name, opts) => ({
        key,
        port,
        name,
        required: Boolean(opts.required),
        listening: opts.alwaysListening ? true : Boolean(cfg.services[key]),
        canToggleListening: !opts.alwaysListening,
        published: Boolean(cfg.expose[key]),
        listeningNote: opts.listeningNote,
        note: opts.note,
    });

    return [
        row('p2p', p.p2p, 'P2P', {
            required: true,
            alwaysListening: true,
            listeningNote: 'A node without peers is not a node, so this always listens.',
            note: 'Peers dial in here. Publish it to become a public node.',
        }),
        row('grpc', p.grpc, 'gRPC', {
            listeningNote: 'Off runs the node with --nogrpc. The stratum bridge needs this on.',
            note: 'Wallets and tools. Publishing exposes it beyond this machine.',
        }),
        row('borsh', p.borsh, 'wRPC Borsh', {
            listeningNote: 'Off drops the listener. The KaChat indexer needs this on.',
            note: 'Rusty/KDX style clients.',
        }),
        row('json', p.json, 'wRPC JSON', {
            alwaysListening: true,
            listeningNote: 'This panel talks to the node over wRPC JSON, so it always listens internally.',
            note: 'Browser and JSON clients. Publishing exposes it beyond this machine.',
        }),
    ];
}

/**
 * Applies a change to one port. The two states are independent controls but not
 * independent facts: a published port that is not listening is a mapping to
 * nothing, and publishing something implies it must be bound. Rather than let
 * the UI offer a state the node cannot be in, the dependent value moves with it.
 */
export function setPortState(cfg, key, { listening, published } = {}) {
    const entry = portMatrix(cfg).find((e) => e.key === key);
    if (!entry) throw new Error(`Unknown port "${key}".`);
    const changes = [];

    if (listening !== undefined && entry.canToggleListening && listening !== entry.listening) {
        cfg.services[key] = listening;
        changes.push(listening ? `${entry.name} listener on` : `${entry.name} listener off`);
        if (!listening && cfg.expose[key]) {
            cfg.expose[key] = false;
            changes.push(`${entry.name} unpublished (a published port that is not listening maps to nothing)`);
        }
    }

    if (published !== undefined && published !== entry.published) {
        cfg.expose[key] = published;
        changes.push(published ? `${entry.name} published on the host` : `${entry.name} no longer published`);
        if (published && entry.canToggleListening && !cfg.services[key]) {
            cfg.services[key] = true;
            changes.push(`${entry.name} listener switched on (publishing needs it bound)`);
        }
    }

    return changes;
}
