import fs from 'node:fs';
import { KASPAD_ARGS_FILE, PORTS_OVERRIDE } from './paths.js';
import { NETWORKS } from './store.js';

export const ports = (cfg) => NETWORKS[cfg.network] ?? NETWORKS.mainnet;

const isBlank = (v) => v === null || v === undefined || `${v}`.trim() === '';

const PINNED = new Set(['p2p', 'json']);
const LEVELS = ['off', 'local', 'public'];
const bindFor = (level) => (level === 'public' ? '0.0.0.0' : level === 'local' ? '127.0.0.1' : null);
const level = (cfg, key) => {
    const v = cfg.expose?.[key];
    if (LEVELS.includes(v)) return v;
    // Tolerate an unmigrated boolean config until migration runs at boot.
    if (v === true) return 'public';
    if (PINNED.has(key)) return 'local';
    return 'off';
};

/**
 * Which listeners kaspad binds inside its container, worked out rather than
 * stored. P2P and wRPC-JSON are always on -- the node needs one, this panel
 * needs the other. gRPC and wRPC-Borsh come on when a port is published (you
 * cannot map a host port to a listener that is not there) OR when a sibling
 * container speaks to it over the docker network: the stratum bridge dials
 * gRPC, the KaChat indexer and bot dial wRPC-Borsh. Passing those needs in as
 * `siblings` keeps this the single source of truth for what is bound.
 */
export function listeners(cfg, siblings = {}) {
    return {
        p2p: true,
        json: true,
        grpc: level(cfg, 'grpc') !== 'off' || Boolean(siblings.mining) || Boolean(siblings.bot),
        borsh: level(cfg, 'borsh') !== 'off' || Boolean(siblings.indexer) || Boolean(siblings.bot),
    };
}

/**
 * Turns the stored node config into the kaspad command line.
 *
 * Every listener binds 0.0.0.0 inside the container. That is not the same as
 * being reachable from the internet: what makes a port public is the published
 * mapping in the compose override (see `renderPortsOverride`). Binding all of
 * them keeps them addressable on the internal docker network, which is how the
 * manager reaches wRPC-JSON and how the nginx proxy reaches any of them.
 *
 * --appdir, --yes and --utxoindex are NOT emitted here; the container
 * entrypoint prepends them. --utxoindex is a setting now, but it still cannot
 * be written as an argument: an older kaspad image force-adds it, and kaspad
 * refuses to start when the flag appears twice. So the choice travels as the
 * `# utxoindex-managed:` marker in the header instead, which an old entrypoint
 * ignores and a new one obeys.
 */
export function buildArgs(cfg, siblings = {}) {
    const p = ports(cfg);
    const args = [...(NETWORKS[cfg.network]?.args ?? [])];
    const on = listeners(cfg, siblings);

    args.push(`--listen=0.0.0.0:${p.p2p}`);

    if (on.grpc) {
        args.push(`--rpclisten=0.0.0.0:${p.grpc}`);
    } else {
        args.push('--nogrpc');
    }
    if (on.borsh) args.push(`--rpclisten-borsh=0.0.0.0:${p.borsh}`);
    // wRPC-JSON is the manager's control channel, so it is unconditional.
    args.push(`--rpclisten-json=0.0.0.0:${p.json}`);

    const f = cfg.flags;
    if (f.archival) args.push('--archival');
    if (f.unsaferpc) args.push('--unsaferpc');
    if (f.perfMetrics) args.push('--perf-metrics');
    if (f.disableUpnp) args.push('--disable-upnp');
    if (f.noDnsSeed) args.push('--nodnsseed');
    if (f.enableUnsyncedMining) args.push('--enable-unsynced-mining');
    if (f.sanity) args.push('--sanity');
    if (f.noLogFiles) args.push('--nologfiles');

    const t = cfg.tuning;
    if (!isBlank(t.logLevel)) args.push(`--loglevel=${t.logLevel}`);
    if (!isBlank(t.outpeers)) args.push(`--outpeers=${t.outpeers}`);
    if (!isBlank(t.maxinpeers)) args.push(`--maxinpeers=${t.maxinpeers}`);
    if (!isBlank(t.rpcmaxclients)) args.push(`--rpcmaxclients=${t.rpcmaxclients}`);
    if (!isBlank(t.maxTrackedAddresses) && Number(t.maxTrackedAddresses) > 0) {
        args.push(`--max-tracked-addresses=${t.maxTrackedAddresses}`);
    }
    if (!isBlank(t.ramScale) && Number(t.ramScale) !== 1) args.push(`--ram-scale=${t.ramScale}`);
    if (!isBlank(t.retentionPeriodDays)) args.push(`--retention-period-days=${t.retentionPeriodDays}`);
    if (!isBlank(t.asyncThreads)) args.push(`--async-threads=${t.asyncThreads}`);
    if (!isBlank(t.rocksdbPreset)) args.push(`--rocksdb-preset=${t.rocksdbPreset}`);

    const n = cfg.peering;
    if (!isBlank(n.externalip)) args.push(`--externalip=${n.externalip.trim()}`);
    if (!isBlank(n.uacomment)) args.push(`--uacomment=${n.uacomment.trim()}`);
    for (const peer of n.connectPeers ?? []) if (!isBlank(peer)) args.push(`--connect=${peer.trim()}`);
    for (const peer of n.addPeers ?? []) if (!isBlank(peer)) args.push(`--addpeer=${peer.trim()}`);

    for (const extra of cfg.extraArgs ?? []) if (!isBlank(extra)) args.push(extra.trim());

    return args;
}

export function writeArgsFile(cfg, siblings = {}) {
    const args = buildArgs(cfg, siblings);
    const header = [
        '# Generated by the Kaspa Node Control panel - edits here are overwritten.',
        '# One argument per line. --appdir and --yes are always added by the',
        '# container entrypoint and cannot be disabled.',
        // The UTXO index setting, carried as a marker rather than an argument.
        // kaspad has no --no-utxoindex and refuses a repeated --utxoindex, so
        // an argument would either be unexpressible or collide with the copy an
        // older image's entrypoint adds. A marker does neither: an entrypoint
        // that predates it ignores the comment and keeps forcing the index on,
        // which is what those installs were already doing.
        `# utxoindex-managed: ${cfg.flags.utxoindex ? 'on' : 'off'}`,
        '',
    ].join('\n');
    fs.writeFileSync(KASPAD_ARGS_FILE, `${header}${args.join('\n')}\n`, 'utf8');
    return args;
}

/**
 * Compose concatenates `ports` across files, so the base compose file leaves
 * kaspad's list empty and this override owns it entirely. Rewriting this file
 * and running `docker compose up -d kaspad` is what opens or closes a port.
 */
export function renderPortsOverride(cfg) {
    const p = ports(cfg);
    // Each port carries its own address now: 'local' binds 127.0.0.1 (this
    // machine only), 'public' binds 0.0.0.0 (the network), 'off' publishes
    // nothing. A port must never reach the network unless it was set 'public'
    // on purpose, so there is no fallback address to get wrong.
    const rows = [
        ['p2p', p.p2p],
        ['grpc', p.grpc],
        ['borsh', p.borsh],
        ['json', p.json],
    ];
    const mappings = [];
    for (const [key, port] of rows) {
        const bind = bindFor(level(cfg, key));
        if (bind) mappings.push({ port, bind });
    }

    const lines = [
        '# Generated by the Kaspa Node Control panel - edits here are overwritten.',
        '# Published host ports for kaspad. Removing a mapping makes the port',
        '# reachable only from the internal docker network.',
        'services:',
        '  kaspad:',
        '    ports:',
    ];
    if (mappings.length === 0) lines.push('      []');
    for (const { bind, port } of mappings) lines.push(`      - "${bind}:${port}:${port}/tcp"`);

    fs.writeFileSync(PORTS_OVERRIDE, `${lines.join('\n')}\n`, 'utf8');
    return mappings.map((m) => m.port);
}

/** The ports a user has to open on their router/firewall to go public. */
export function publicPorts(cfg) {
    return portMatrix(cfg)
        .filter((e) => e.exposure === 'public')
        .map(({ port, name, required }) => ({ port, name, required }));
}

/**
 * Every port the node can offer, described as one control with three settings.
 *
 *   exposure  'off' | 'local' | 'public' -- the whole reachability story for
 *             the port: off publishes nothing, local publishes on 127.0.0.1,
 *             public publishes on 0.0.0.0. The UI shows it as two switches
 *             (Local, then Public on top of it), so `local` and `public` are
 *             the derived booleans for those.
 *
 * The in-container listener is not a control here -- it follows what needs it
 * (`listeners`), so `forcedListen` just flags a port whose listener a sibling
 * holds on even while it is unpublished, to explain why it still shows a light.
 *
 * P2P and wRPC-JSON are `pinned`: they cannot go off, so their Local switch
 * reads "always". Listing off ports too is deliberate: hiding a switched-off
 * port would leave no way back on.
 */
export function portMatrix(cfg, siblings = {}) {
    const p = ports(cfg);
    const on = listeners(cfg, siblings);
    const row = (key, port, name, opts) => {
        const exposure = level(cfg, key);
        return {
            key,
            port,
            name,
            required: Boolean(opts.required),
            pinned: Boolean(opts.pinned),
            exposure,
            local: exposure !== 'off',
            public: exposure === 'public',
            listening: on[key],
            forcedListen: !opts.pinned && on[key] && exposure === 'off',
            localNote: opts.localNote,
            publicNote: opts.publicNote,
        };
    };

    return [
        row('p2p', p.p2p, 'P2P', {
            required: true,
            pinned: true,
            localNote: 'A node without peers is not a node, so P2P always runs.',
            publicNote: 'Publish it on 0.0.0.0 to accept inbound peers and become a public node.',
        }),
        row('grpc', p.grpc, 'gRPC', {
            localNote: 'Reachable from this machine on 127.0.0.1. The stratum bridge uses gRPC.',
            publicNote: 'Publishing on 0.0.0.0 exposes it beyond this machine.',
        }),
        row('borsh', p.borsh, 'wRPC Borsh', {
            localNote: 'Reachable from this machine on 127.0.0.1. The KaChat indexer uses wRPC Borsh.',
            publicNote: 'Publishing on 0.0.0.0 exposes it to Rusty/KDX style clients beyond this machine.',
        }),
        row('json', p.json, 'wRPC JSON', {
            pinned: true,
            localNote: 'This panel talks to the node over wRPC JSON, so it is always at least local.',
            publicNote: 'Publishing on 0.0.0.0 exposes it to browser and JSON clients beyond this machine.',
        }),
    ];
}

/**
 * Moves one port between off / local / public. The UI sends one switch at a
 * time: `local` is the base (off <-> local) and `public` sits on top of it
 * (local <-> public). They are not independent -- public implies local, and a
 * port cannot be public without first being reachable -- so the dependent value
 * moves with the one that was changed. Pinned ports (P2P, wRPC-JSON) never drop
 * below local.
 */
export function setPortState(cfg, key, { local, public: pub } = {}) {
    const entry = portMatrix(cfg).find((e) => e.key === key);
    if (!entry) throw new Error(`Unknown port "${key}".`);
    const before = entry.exposure;
    let next = before;

    if (pub === true) next = 'public';
    else if (pub === false && next === 'public') next = 'local';

    if (local === true && next === 'off') next = 'local';
    else if (local === false) next = entry.pinned ? (next === 'public' ? 'public' : 'local') : 'off';

    if (next === before) return [];
    cfg.expose[key] = next;
    const phrase = {
        off: 'off (not published)',
        local: 'reachable from this machine (127.0.0.1)',
        public: 'public on the network (0.0.0.0)',
    };
    return [`${entry.name} -> ${phrase[next]}`];
}
