import fs from 'node:fs';
import { KASPAD_ARGS_FILE, PORTS_OVERRIDE } from './paths.js';
import { NETWORKS } from './store.js';

export const ports = (cfg) => NETWORKS[cfg.network] ?? NETWORKS.mainnet;

const isBlank = (v) => v === null || v === undefined || `${v}`.trim() === '';

/**
 * Turns the stored node config into the kaspad command line.
 *
 * Every listener binds 0.0.0.0 inside the container. That is not the same as
 * being reachable from the internet: what makes a port public is the published
 * mapping in the compose override (see `renderPortsOverride`). Binding all of
 * them keeps them addressable on the internal docker network, which is how the
 * manager reaches wRPC-JSON and how the nginx proxy reaches any of them.
 *
 * --utxoindex, --appdir and --yes are NOT emitted here; the container
 * entrypoint always prepends them so they cannot be switched off from the UI.
 */
export function buildArgs(cfg) {
    const p = ports(cfg);
    const args = [...(NETWORKS[cfg.network]?.args ?? [])];

    args.push(`--listen=0.0.0.0:${p.p2p}`);

    if (cfg.services.grpc) {
        args.push(`--rpclisten=0.0.0.0:${p.grpc}`);
    } else {
        args.push('--nogrpc');
    }
    if (cfg.services.borsh) args.push(`--rpclisten-borsh=0.0.0.0:${p.borsh}`);
    // wRPC-JSON is the manager's control channel, so it is unconditional.
    args.push(`--rpclisten-json=0.0.0.0:${p.json}`);

    const f = cfg.flags;
    if (f.archival) args.push('--archival');
    if (f.unsaferpc) args.push('--unsaferpc');
    if (f.perfMetrics) args.push('--perf-metrics');
    if (f.disableUpnp) args.push('--disable-upnp');
    if (f.noDnsSeed) args.push('--nodnsseed');
    if (f.enableUnsyncedMining) args.push('--enable-unsynced-mining');
    if (f.sanity) args.push('--sanity');
    if (f.noLogFiles) args.push('--nologfiles');

    const t = cfg.tuning;
    if (!isBlank(t.logLevel)) args.push(`--loglevel=${t.logLevel}`);
    if (!isBlank(t.outpeers)) args.push(`--outpeers=${t.outpeers}`);
    if (!isBlank(t.maxinpeers)) args.push(`--maxinpeers=${t.maxinpeers}`);
    if (!isBlank(t.rpcmaxclients)) args.push(`--rpcmaxclients=${t.rpcmaxclients}`);
    if (!isBlank(t.maxTrackedAddresses) && Number(t.maxTrackedAddresses) > 0) {
        args.push(`--max-tracked-addresses=${t.maxTrackedAddresses}`);
    }
    if (!isBlank(t.ramScale) && Number(t.ramScale) !== 1) args.push(`--ram-scale=${t.ramScale}`);
    if (!isBlank(t.retentionPeriodDays)) args.push(`--retention-period-days=${t.retentionPeriodDays}`);
    if (!isBlank(t.asyncThreads)) args.push(`--async-threads=${t.asyncThreads}`);
    if (!isBlank(t.rocksdbPreset)) args.push(`--rocksdb-preset=${t.rocksdbPreset}`);

    const n = cfg.peering;
    if (!isBlank(n.externalip)) args.push(`--externalip=${n.externalip.trim()}`);
    if (!isBlank(n.uacomment)) args.push(`--uacomment=${n.uacomment.trim()}`);
    for (const peer of n.connectPeers ?? []) if (!isBlank(peer)) args.push(`--connect=${peer.trim()}`);
    for (const peer of n.addPeers ?? []) if (!isBlank(peer)) args.push(`--addpeer=${peer.trim()}`);

    for (const extra of cfg.extraArgs ?? []) if (!isBlank(extra)) args.push(extra.trim());

    return args;
}

export function writeArgsFile(cfg) {
    const args = buildArgs(cfg);
    const header = [
        '# Generated by the Kaspa Node Control panel - edits here are overwritten.',
        '# One argument per line. --appdir, --yes and --utxoindex are always added',
        '# by the container entrypoint and cannot be disabled.',
        '',
    ].join('\n');
    fs.writeFileSync(KASPAD_ARGS_FILE, `${header}${args.join('\n')}\n`, 'utf8');
    return args;
}

/**
 * Compose concatenates `ports` across files, so the base compose file leaves
 * kaspad's list empty and this override owns it entirely. Rewriting this file
 * and running `docker compose up -d kaspad` is what opens or closes a port.
 */
export function renderPortsOverride(cfg) {
    const p = ports(cfg);
    const bind = cfg.expose.bindAddress || '0.0.0.0';
    const mappings = [];
    if (cfg.expose.p2p) mappings.push(p.p2p);
    if (cfg.expose.grpc && cfg.services.grpc) mappings.push(p.grpc);
    if (cfg.expose.borsh && cfg.services.borsh) mappings.push(p.borsh);
    if (cfg.expose.json) mappings.push(p.json);

    const lines = [
        '# Generated by the Kaspa Node Control panel - edits here are overwritten.',
        '# Published host ports for kaspad. Removing a mapping makes the port',
        '# reachable only from the internal docker network.',
        'services:',
        '  kaspad:',
        '    ports:',
    ];
    if (mappings.length === 0) lines.push('      []');
    for (const port of mappings) lines.push(`      - "${bind}:${port}:${port}/tcp"`);

    fs.writeFileSync(PORTS_OVERRIDE, `${lines.join('\n')}\n`, 'utf8');
    return mappings;
}

/** The ports a user has to open on their router/firewall to go public. */
export function publicPorts(cfg) {
    return portMatrix(cfg).filter((entry) => entry.on).map(({ port, name, required }) => ({ port, name, required }));
}

/**
 * Every port the node can offer, on or off, for the dashboard's toggles.
 *
 * Listing only the enabled ones would be a trap: switching a port off would
 * remove its own row, leaving no way to switch it back on.
 *
 * `canStopListening` records whether turning the toggle off can also drop the
 * kaspad argument, or only unpublish the host port:
 *   - P2P has no off switch worth having; a node without peers is not a node.
 *   - wRPC JSON is how this panel talks to the node, so its listener stays up
 *     on the internal network whatever the toggle says.
 * In both of those cases "off" still means unreachable from outside, which is
 * what this section is about.
 */
export function portMatrix(cfg) {
    const p = ports(cfg);
    return [
        {
            key: 'p2p',
            port: p.p2p,
            name: 'P2P',
            required: true,
            on: Boolean(cfg.expose.p2p),
            canStopListening: false,
            note: 'Peers connect here. Off unpublishes the port; the node keeps talking to the peers it dials out to.',
        },
        {
            key: 'grpc',
            port: p.grpc,
            name: 'gRPC',
            required: false,
            on: Boolean(cfg.expose.grpc && cfg.services.grpc),
            canStopListening: true,
            note: 'Wallets and tools. Off runs the node with --nogrpc and unpublishes the port.',
        },
        {
            key: 'borsh',
            port: p.borsh,
            name: 'wRPC Borsh',
            required: false,
            on: Boolean(cfg.expose.borsh && cfg.services.borsh),
            canStopListening: true,
            note: 'Rusty/KDX style clients, and what the KaChat indexer reads. Off drops the listener and unpublishes the port.',
        },
        {
            key: 'json',
            port: p.json,
            name: 'wRPC JSON',
            required: false,
            on: Boolean(cfg.expose.json),
            canStopListening: false,
            note: 'Browser and JSON clients. Off unpublishes the port; the listener stays on the internal network for this panel.',
        },
    ];
}

/**
 * Applies a dashboard toggle to the stored config. Where a listener can be shut
 * down as well as unpublished, both move together, so "off" means the node is
 * genuinely started without that argument rather than merely firewalled.
 */
export function setPortEnabled(cfg, key, enabled) {
    const entry = portMatrix(cfg).find((e) => e.key === key);
    if (!entry) throw new Error(`Unknown port "${key}".`);

    cfg.expose[key] = enabled;
    if (entry.canStopListening) cfg.services[key] = enabled;
    return cfg;
}
