import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { LETSENCRYPT_DIR, NGINX_CONF_D, NGINX_SNIPPETS } from './paths.js';
import { docker, PROXY_CONTAINER } from './dockerctl.js';
import { htpasswdLine } from './auth.js';
import { ports } from './kaspad-args.js';

const DOMAIN_RE = /^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$/;
const ID_RE = /^[a-f0-9]{12}$/;

export const newId = () => crypto.randomBytes(6).toString('hex');

export const TARGET_KINDS = {
    borsh: { label: 'Kaspad wRPC Borsh', websocket: true, grpc: false },
    json: { label: 'Kaspad wRPC JSON', websocket: true, grpc: false },
    grpc: { label: 'Kaspad gRPC', websocket: false, grpc: true },
    manager: { label: 'This control panel', websocket: false, grpc: false },
    custom: { label: 'Custom host:port', websocket: false, grpc: false },
};

/** Throws on anything that would let a value escape into the nginx grammar. */
export function validateProxy(proxy, { existing = [], panelHasPassword = true } = {}) {
    const errors = [];
    const domain = String(proxy.domain || '').trim().toLowerCase();

    // Publishing the panel is the one way to undo the "it is only on loopback"
    // assumption that lets it run without a password. nginx reaches the manager
    // over the internal network no matter what the panel is bound to, so this
    // has to be caught here rather than by the port binding.
    if (proxy.target?.kind === 'manager' && !panelHasPassword && !proxy.auth?.enabled) {
        errors.push(
            'This panel has no admin password, so it cannot be put on a domain. ' +
                'Either tick "Require a username and password" for this host, or re-run the ' +
                'installer with --password to set one.',
        );
    }

    if (!domain) errors.push('Domain is required.');
    else if (domain.length > 253 || !DOMAIN_RE.test(domain)) errors.push(`"${domain}" is not a valid domain name.`);
    else if (existing.some((p) => p.id !== proxy.id && p.domain === domain)) {
        errors.push(`Another proxy host already uses ${domain}.`);
    }

    if (!TARGET_KINDS[proxy.target?.kind]) errors.push('Unknown target type.');

    if (proxy.target?.kind === 'custom') {
        const host = String(proxy.target.host || '').trim();
        if (!host || !/^[A-Za-z0-9._-]{1,253}$/.test(host)) errors.push('Custom target host is invalid.');
        const port = Number(proxy.target.port);
        if (!Number.isInteger(port) || port < 1 || port > 65535) errors.push('Custom target port must be 1-65535.');
        if (!['http', 'https'].includes(proxy.target.scheme || 'http')) errors.push('Custom scheme must be http or https.');
    }

    if (proxy.ssl?.mode === 'letsencrypt' && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(proxy.ssl.email || ''))) {
        errors.push("A contact e-mail is required for Let's Encrypt certificates.");
    }

    if (proxy.auth?.enabled) {
        if (!/^[A-Za-z0-9._-]{1,64}$/.test(String(proxy.auth.user || ''))) errors.push('Basic-auth user is invalid.');
        const hasStored = Boolean(proxy.auth.htpasswd);
        if (!hasStored && String(proxy.auth.password || '').length < 6) {
            errors.push('Basic-auth password must be at least 6 characters.');
        }
    }

    for (const entry of proxy.allowlist ?? []) {
        if (!/^[0-9a-fA-F.:]+(\/\d{1,3})?$/.test(String(entry).trim())) errors.push(`"${entry}" is not a valid IP or CIDR.`);
    }

    if (proxy.id && !ID_RE.test(proxy.id)) errors.push('Invalid proxy id.');

    return errors;
}

/** Resolves a proxy target to the upstream nginx should talk to. */
export function upstreamFor(proxy, nodeConfig) {
    const p = ports(nodeConfig);
    switch (proxy.target.kind) {
        case 'borsh':
            return { scheme: 'http', host: 'kaspad', port: p.borsh, websocket: true, grpc: false };
        case 'json':
            return { scheme: 'http', host: 'kaspad', port: p.json, websocket: true, grpc: false };
        case 'grpc':
            return { scheme: 'grpc', host: 'kaspad', port: p.grpc, websocket: false, grpc: true };
        case 'manager':
            return { scheme: 'http', host: 'manager', port: 8080, websocket: true, grpc: false };
        default:
            return {
                scheme: proxy.target.scheme || 'http',
                host: proxy.target.host,
                port: Number(proxy.target.port),
                websocket: Boolean(proxy.websocket),
                grpc: false,
            };
    }
}

export const certPath = (domain) => path.join(LETSENCRYPT_DIR, 'live', domain, 'fullchain.pem');
export const hasCertificate = (domain) => fs.existsSync(certPath(domain));

// ------------------------------------------------------------- rendering ----

const BASE_CONF = `# Generated by the Kaspa Node Control panel - edits here are overwritten.
#
# The map below turns a websocket upgrade request into the right Connection
# header; kaspad's wRPC endpoints are websockets, so proxying them needs it.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Served for every domain so a certificate can be issued before the vhost
    # for that domain exists.
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 404 "No proxy host is configured for this domain.\\n";
    }
}
`;

function locationBlock(up, proxy, indent = '        ') {
    const i = indent;
    const lines = [];
    if (up.grpc) {
        lines.push(`${i}grpc_pass grpc://${up.host}:${up.port};`);
        lines.push(`${i}grpc_read_timeout 3600s;`);
        lines.push(`${i}grpc_send_timeout 3600s;`);
        return lines.join('\n');
    }
    lines.push(`${i}proxy_pass ${up.scheme}://${up.host}:${up.port};`);
    lines.push(`${i}proxy_http_version 1.1;`);
    lines.push(`${i}proxy_set_header Host $host;`);
    lines.push(`${i}proxy_set_header X-Real-IP $remote_addr;`);
    lines.push(`${i}proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
    lines.push(`${i}proxy_set_header X-Forwarded-Proto $scheme;`);
    if (up.websocket) {
        lines.push(`${i}proxy_set_header Upgrade $http_upgrade;`);
        lines.push(`${i}proxy_set_header Connection $connection_upgrade;`);
        // wRPC connections are long lived and mostly idle between notifications.
        lines.push(`${i}proxy_read_timeout 3600s;`);
        lines.push(`${i}proxy_send_timeout 3600s;`);
    } else {
        lines.push(`${i}proxy_read_timeout 300s;`);
    }
    lines.push(`${i}proxy_buffering off;`);
    if (proxy.auth?.enabled) {
        lines.push(`${i}auth_basic "Restricted";`);
        lines.push(`${i}auth_basic_user_file /etc/nginx/snippets/${proxy.id}.htpasswd;`);
    }
    for (const entry of proxy.allowlist ?? []) lines.push(`${i}allow ${String(entry).trim()};`);
    if ((proxy.allowlist ?? []).length) lines.push(`${i}deny all;`);
    if (proxy.rateLimit) lines.push(`${i}limit_req zone=kz_${proxy.id} burst=${Number(proxy.rateLimit) * 2} nodelay;`);
    return lines.join('\n');
}

export function renderProxy(proxy, nodeConfig) {
    const up = upstreamFor(proxy, nodeConfig);
    const domain = proxy.domain;
    const useTls = proxy.ssl?.mode === 'letsencrypt' && hasCertificate(domain);
    const forceHttps = useTls && proxy.ssl?.forceHttps !== false;
    const out = [`# Generated by the Kaspa Node Control panel - edits here are overwritten.`];

    if (proxy.rateLimit) {
        out.push(`limit_req_zone $binary_remote_addr zone=kz_${proxy.id}:10m rate=${Number(proxy.rateLimit)}r/s;`);
    }

    out.push('');
    out.push('server {');
    out.push('    listen 80;');
    out.push('    listen [::]:80;');
    // gRPC over plaintext is h2c. Since nginx 1.25.1 `http2 on` accepts both
    // h2c and HTTP/1.1 on the same listener, so the ACME challenge still works.
    if (up.grpc) out.push('    http2 on;');
    out.push(`    server_name ${domain};`);
    out.push('');
    out.push('    location /.well-known/acme-challenge/ {');
    out.push('        root /var/www/certbot;');
    out.push('        default_type "text/plain";');
    out.push('    }');
    out.push('');
    if (forceHttps) {
        out.push('    location / {');
        out.push('        return 301 https://$host$request_uri;');
        out.push('    }');
    } else {
        out.push('    location / {');
        out.push(locationBlock(up, proxy));
        out.push('    }');
    }
    out.push('}');

    if (useTls) {
        out.push('');
        out.push('server {');
        out.push(`    listen 443 ssl${up.grpc ? ' http2' : ''};`);
        out.push(`    listen [::]:443 ssl${up.grpc ? ' http2' : ''};`);
        if (!up.grpc) out.push('    http2 on;');
        out.push(`    server_name ${domain};`);
        out.push('');
        out.push(`    ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;`);
        out.push(`    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;`);
        out.push('    ssl_protocols TLSv1.2 TLSv1.3;');
        out.push('    ssl_prefer_server_ciphers off;');
        out.push('    ssl_session_cache shared:SSL:10m;');
        out.push('    ssl_session_timeout 1d;');
        out.push('    add_header Strict-Transport-Security "max-age=31536000" always;');
        out.push('');
        out.push('    client_max_body_size 32m;');
        out.push('');
        out.push('    location / {');
        out.push(locationBlock(up, proxy));
        out.push('    }');
        out.push('}');
    }

    if (proxy.customSnippet?.trim()) {
        out.push('');
        out.push('# --- custom snippet ---');
        out.push(proxy.customSnippet.trim());
    }

    return `${out.join('\n')}\n`;
}

/**
 * Rewrites the whole conf.d directory from the stored proxy list. Regenerating
 * everything (rather than patching) keeps the directory a pure function of the
 * saved state, so a half-applied change can never linger.
 */
export function writeAll(proxies, nodeConfig) {
    fs.mkdirSync(NGINX_CONF_D, { recursive: true });
    fs.mkdirSync(NGINX_SNIPPETS, { recursive: true });

    fs.writeFileSync(path.join(NGINX_CONF_D, '00-default.conf'), BASE_CONF, 'utf8');

    const keep = new Set(['00-default.conf']);
    for (const proxy of proxies) {
        const file = `10-${proxy.id}.conf`;
        keep.add(file);
        if (proxy.enabled === false) {
            fs.writeFileSync(
                path.join(NGINX_CONF_D, file),
                `# ${proxy.domain} is disabled in the control panel.\n`,
                'utf8',
            );
        } else {
            fs.writeFileSync(path.join(NGINX_CONF_D, file), renderProxy(proxy, nodeConfig), 'utf8');
        }
        const htpasswd = path.join(NGINX_SNIPPETS, `${proxy.id}.htpasswd`);
        if (proxy.auth?.enabled && proxy.auth.htpasswd) {
            fs.writeFileSync(htpasswd, `${proxy.auth.htpasswd}\n`, 'utf8');
        } else if (fs.existsSync(htpasswd)) {
            fs.rmSync(htpasswd);
        }
    }

    for (const file of fs.readdirSync(NGINX_CONF_D)) {
        if (file.endsWith('.conf') && !keep.has(file)) fs.rmSync(path.join(NGINX_CONF_D, file));
    }
}

export function storeBasicAuth(proxy) {
    if (proxy.auth?.enabled && proxy.auth.password) {
        proxy.auth.htpasswd = htpasswdLine(proxy.auth.user, proxy.auth.password);
    }
    if (proxy.auth) delete proxy.auth.password;
    return proxy;
}

// ------------------------------------------------------------ nginx control --

export async function testConfig() {
    const { stdout, stderr } = await docker(['exec', PROXY_CONTAINER, 'nginx', '-t']);
    return `${stdout}${stderr}`.trim();
}

export async function reload() {
    await testConfig();
    await docker(['exec', PROXY_CONTAINER, 'nginx', '-s', 'reload']);
}
